# -*- coding: utf-8 -*-
"""ICV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wevHf3e2cdqffV-NB4V4Mjf_4reeChN8
"""

#Calculate mean waveform template
group0wave=[]
group1wave=[]
group2wave=[]

#group refers to the output variable from either feature extraction algorithms

for i in range(group.shape[0]):
  if group[i]==0:
    group0wave.append(GTaligned[i])
  elif group[i]==1:
    group1wave.append(GTaligned[i])
  elif group[i]==2:
    group2wave.append(GTaligned[i])

group0wave=np.array(group0wave)
group1wave=np.array(group1wave)
group2wave=np.array(group2wave)

print(group0wave.shape)
print(group1wave.shape)
print(group2wave.shape)

group0mean=np.mean(group0wave,axis=0)
group1mean=np.mean(group1wave,axis=0)
group2mean=np.mean(group2wave,axis=0)
print(group0mean.shape)


#ICV 

sum0=0
sum1=0
sum2=0

for i in range(group.shape[0]):
  if group[i]==0:
    sum0=sum0+np.linalg.norm(GTaligned[i]-group0mean)
  elif group[i]==1:
    sum1=sum1+np.linalg.norm(GTaligned[i]-group1mean)
  elif group[i]==2:
    sum2=sum2+np.linalg.norm(GTaligned[i]-group2mean)
  
ICV0=sum0/group0wave.shape[0]
ICV1=sum1/group1wave.shape[0]
ICV2=sum2/group2wave.shape[0]

print(ICV0)
print(ICV1)
print(ICV2)